### ISSUE TITLE
--config - using any configuration other than "production" causes a config error, however, this error is not clear

### ISSUE THREAD

**Issue by rob256** [Percona-Lab/mongodb_consistent_backup#186]
The config parses fine when `production` is used. As per:
```
production:
    host: some.mongo.host
    port: 27018
    backup:
        method: mongodump
        name: dump1
        location: /tmp/backup
```

However, using the following configuration causes the following:
```
development:
    host: some.mongo.host
    port: 27018
    backup:
        method: mongodump
        name: dump1
        location: /tmp/backup
```

```
Error setting up configuration: 'Field "backup.name" must be set via command-line or config file!'!
```

This error is very unclear.
